name: Call a reusable workflow

on:
  pull_request:
    branches:
      - int

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-workflow-1.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.PAT }}